#!/usr/bin/env bash
# Submit a bounded terminal-reward L2 GRPO run. Defaults to a 1-group smoke.
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-/fs/gamma-projects/vlm-robot/Video_Skills}"
OUTPUT_ROOT="${OUTPUT_ROOT:-${REPO_ROOT}/dataset_clip_wrapper/output/l2_terminal_grpo_$(date +%Y%m%d_%H%M%S)}"
mkdir -p "${OUTPUT_ROOT}/slurm_logs"
sbatch_args=(
  --parsable
  --job-name="vs-l2-terminal-grpo" \
  --partition="${PARTITION:-scavenger}" --account="${ACCOUNT:-scavenger}" \
  --gres="${GRES:-gpu:h100-sxm:1}" --cpus-per-task="${CPUS:-8}" --mem="${MEM:-64G}" \
  --time="${WALLTIME:-04:00:00}" \
  --output="${OUTPUT_ROOT}/slurm_logs/train-%j.out" \
  --error="${OUTPUT_ROOT}/slurm_logs/train-%j.err" \
  --export="ALL,REPO_ROOT=${REPO_ROOT},OUTPUT_ROOT=${OUTPUT_ROOT},DATASET_ROOT=${DATASET_ROOT:-/fs/gamma-projects/vlm-robot/datasets},FROZEN_L1_GLOBS=${FROZEN_L1_GLOBS:-},SPLIT_ROLE=${SPLIT_ROLE:-grpo_pool},MAX_GROUPS=${MAX_GROUPS:-1},REPEATS_PER_EXAMPLE=${REPEATS_PER_EXAMPLE:-1},REPEAT_START_INDEX=${REPEAT_START_INDEX:-0},K=${K:-2},CG_TOPK=${CG_TOPK:-2},VIDEO_HOLMES_TOPK=${VIDEO_HOLMES_TOPK:-4},PPO_EPOCHS=${PPO_EPOCHS:-1},LEARNING_RATE=${LEARNING_RATE:-2e-6},KL_COEF=${KL_COEF:-0.05},CLIP_EPS=${CLIP_EPS:-0.2},TEMPERATURE=${TEMPERATURE:-0.9},POINTWISE_TEMPERATURE=${POINTWISE_TEMPERATURE:-},POINTWISE_TRAIN_BATCH_SIZE=${POINTWISE_TRAIN_BATCH_SIZE:-1},CHECKPOINT_EVERY_GROUPS=${CHECKPOINT_EVERY_GROUPS:-10},MAX_NEW_TOKENS=${MAX_NEW_TOKENS:-384},GENERATION_TIMEOUT_S=${GENERATION_TIMEOUT_S:-90},ROLLOUT_TIMEOUT_S=${ROLLOUT_TIMEOUT_S:-240},PLANNER_MODEL=${PLANNER_MODEL:-openai/gpt-oss-120b},SKILL_MODEL=${SKILL_MODEL:-qwen/qwen3.5-9b},PLANNER_TIMEOUT_S=${PLANNER_TIMEOUT_S:-180},SKILL_TIMEOUT_S=${SKILL_TIMEOUT_S:-90},EXECUTOR_CACHE_DIR=${EXECUTOR_CACHE_DIR:-},SEED=${SEED:-42},CONDA_ENV=${CONDA_ENV:-/fs/gamma-projects/vlm-robot/conda/envs/video-skills-grpo},KEYS_PY=${KEYS_PY:-/fs/gamma-projects/vlm-robot/keys.py},SFT_ADAPTER=${SFT_ADAPTER:-},DATASET_ADAPTERS=${DATASET_ADAPTERS:-},BOUNDARY_ANCHOR_INDEX0=${BOUNDARY_ANCHOR_INDEX0:-0},ALLOW_SDPA_FALLBACK=${ALLOW_SDPA_FALLBACK:-0},EVAL_ONLY=${EVAL_ONLY:-0},RETRIEVAL_ONLY=${RETRIEVAL_ONLY:-0},PROCESS_REWARD_WARMUP=${PROCESS_REWARD_WARMUP:-0},TERMINAL_ON_PROCESS_HIT=${TERMINAL_ON_PROCESS_HIT:-0},POINTWISE_ACTION_POLICY=${POINTWISE_ACTION_POLICY:-0},POINTWISE_ACTION_DATASETS=${POINTWISE_ACTION_DATASETS:-video_holmes},DATASETS=${DATASETS:-},EXAMPLE_ID_ALLOWLIST=${EXAMPLE_ID_ALLOWLIST:-},PRESERVE_ALLOWLIST_ORDER=${PRESERVE_ALLOWLIST_ORDER:-0},DATASET_BALANCED_SAMPLING=${DATASET_BALANCED_SAMPLING:-0},REQUIRE_PROCESS_SUPERVISION=${REQUIRE_PROCESS_SUPERVISION:-0},MIN_CATALOG_SIZE=${MIN_CATALOG_SIZE:-1},MAX_CATALOG_SIZE=${MAX_CATALOG_SIZE:-},RELEASE_GATE_FILES=${RELEASE_GATE_FILES:-},MINING_REPORT=${MINING_REPORT:-},MIN_ELIGIBLE_GROUPS_PER_DATASET=${MIN_ELIGIBLE_GROUPS_PER_DATASET:-},MIN_TRAINABLE_GROUP_RATE=${MIN_TRAINABLE_GROUP_RATE:-0.25}" \
)
if [[ -n "${DEPENDENCY:-}" ]]; then
  sbatch_args+=(--dependency="${DEPENDENCY}")
fi
if [[ -n "${QOS:-}" ]]; then
  sbatch_args+=(--qos="${QOS}")
fi
sbatch_args+=("${REPO_ROOT}/scripts/grpo/run_l2_terminal_on_policy.sh")
jobid=$(sbatch "${sbatch_args[@]}")
echo "OUTPUT_ROOT=${OUTPUT_ROOT}"
echo "l2-terminal-grpo -> ${jobid}"
